[package]
name = "Quick"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lenguaje = { version = "0.1.0", path = "lenguaje" }
quiken = { version = "0.1.0", path = "quiken" }
colored = "2.0.4"
